using Jr.Backend.Fornecedores.Domain.ValueObjects;
using System;
using System.Collections.Generic;

namespace Jr.Backend.Fornecedores.Domain.Commands.Response
{
    public class AtualizarFornecedorCommandResponse : Fornecedor
    {
        public AtualizarFornecedorCommandResponse(int capitalSocial, int cnaeFiscal, string cnaeFiscalDescricao, List<CnaesSecundario> cnaesSecundarios, string cnpj, int codigoNaturezaJuridica, DateTime dataExclusaoDoSimples, DateTime dataInicioAtividade, DateTime dataOpcaoPeloSimples, DateTime dataSituacaoCadastral, DateTime dataSituacaoEspecial, string descricaoMatrizFilial, string descricaoPorte, string descricaoSituacaoCadastral, List<Endereco> enderecos, int identificadorMatrizFilial, int motivoSituacaoCadastral, string nomeCidadeExterior, string nomeFantasia, bool opcaoPeloMei, bool opcaoPeloSimples, int porte, List<Qsa> qsa, int qualificacaoDoResponsavel, string razaoSocial, int situacaoCadastral, string situacaoEspecial, IEnumerable<string> telefones) : base(capitalSocial, cnaeFiscal, cnaeFiscalDescricao, cnaesSecundarios, cnpj, codigoNaturezaJuridica, dataExclusaoDoSimples, dataInicioAtividade, dataOpcaoPeloSimples, dataSituacaoCadastral, dataSituacaoEspecial, descricaoMatrizFilial, descricaoPorte, descricaoSituacaoCadastral, enderecos, identificadorMatrizFilial, motivoSituacaoCadastral, nomeCidadeExterior, nomeFantasia, opcaoPeloMei, opcaoPeloSimples, porte, qsa, qualificacaoDoResponsavel, razaoSocial, situacaoCadastral, situacaoEspecial, telefones)
        {
        }

        public AtualizarFornecedorCommandResponse(Guid id, bool aceiteTermosDeUso, int capitalSocial, string celular, int cnaeFiscal, string cnaeFiscalDescricao, List<CnaesSecundario> cnaesSecundarios, string cnpj, int codigoNaturezaJuridica, DateTime dataCadastro, DateTime dataExclusaoDoSimples, DateTime dataInicioAtividade, DateTime dataOpcaoPeloSimples, DateTime dataSituacaoCadastral, DateTime dataSituacaoEspecial, string descricaoMatrizFilial, string descricaoPorte, string descricaoSituacaoCadastral, IEnumerable<string> emailContato, IEnumerable<string> emailFatura, List<Endereco> enderecos, int identificadorMatrizFilial, InformacoesBancarias informacoesBancarias, int motivoSituacaoCadastral, string nomeCidadeExterior, string nomeContato, string nomeFantasia, bool opcaoPeloMei, bool opcaoPeloSimples, int porte, List<Qsa> qsa, int qualificacaoDoResponsavel, string razaoSocial, int situacaoCadastral, string situacaoEspecial, IEnumerable<string> telefones) : base(id, aceiteTermosDeUso, capitalSocial, celular, cnaeFiscal, cnaeFiscalDescricao, cnaesSecundarios, cnpj, codigoNaturezaJuridica, dataCadastro, dataExclusaoDoSimples, dataInicioAtividade, dataOpcaoPeloSimples, dataSituacaoCadastral, dataSituacaoEspecial, descricaoMatrizFilial, descricaoPorte, descricaoSituacaoCadastral, emailContato, emailFatura, enderecos, identificadorMatrizFilial, informacoesBancarias, motivoSituacaoCadastral, nomeCidadeExterior, nomeContato, nomeFantasia, opcaoPeloMei, opcaoPeloSimples, porte, qsa, qualificacaoDoResponsavel, razaoSocial, situacaoCadastral, situacaoEspecial, telefones)
        {
        }

        public AtualizarFornecedorCommandResponse(bool aceiteTermosDeUso, int capitalSocial, string celular, int cnaeFiscal, string cnaeFiscalDescricao, List<CnaesSecundario> cnaesSecundarios, string cnpj, int codigoNaturezaJuridica, DateTime dataCadastro, DateTime dataExclusaoDoSimples, DateTime dataInicioAtividade, DateTime dataOpcaoPeloSimples, DateTime dataSituacaoCadastral, DateTime dataSituacaoEspecial, string descricaoMatrizFilial, string descricaoPorte, string descricaoSituacaoCadastral, IEnumerable<string> emailContato, IEnumerable<string> emailFatura, List<Endereco> enderecos, int identificadorMatrizFilial, InformacoesBancarias informacoesBancarias, int motivoSituacaoCadastral, string nomeCidadeExterior, string nomeContato, string nomeFantasia, bool opcaoPeloMei, bool opcaoPeloSimples, int porte, List<Qsa> qsa, int qualificacaoDoResponsavel, string razaoSocial, int situacaoCadastral, string situacaoEspecial, IEnumerable<string> telefones) : base(aceiteTermosDeUso, capitalSocial, celular, cnaeFiscal, cnaeFiscalDescricao, cnaesSecundarios, cnpj, codigoNaturezaJuridica, dataCadastro, dataExclusaoDoSimples, dataInicioAtividade, dataOpcaoPeloSimples, dataSituacaoCadastral, dataSituacaoEspecial, descricaoMatrizFilial, descricaoPorte, descricaoSituacaoCadastral, emailContato, emailFatura, enderecos, identificadorMatrizFilial, informacoesBancarias, motivoSituacaoCadastral, nomeCidadeExterior, nomeContato, nomeFantasia, opcaoPeloMei, opcaoPeloSimples, porte, qsa, qualificacaoDoResponsavel, razaoSocial, situacaoCadastral, situacaoEspecial, telefones)
        {
        }
    }
}